version: "3.8"
services: 
  seek:
    build:
      context: .
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - 5555:5000
    environment: 
      - FLASK_ENV=${FLASK_ENV}
      - DB_URL=${DB_URL}
      - DB_TEST_URL=${DB_TEST_URL}
    depends_on: 
      - database
  
  database:
    build:
      context: ./seek/db 
    expose: 
      - 5432
    environment: 
      - PG_USER={PG_USER}
      - PG_PASSWORD={PG_PASSWORD}


