version: "3.8"
services: 
  seek:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
    ports:
      - 5555:5000
    environment: 
      - DATABASE_URL=${DATABASE_URL}
      - APP_SETTINGS=seek.config.Production
      - APP_KEY=${APP_KEY}
      - PORT=5000
    depends_on: 
      - api-db
  
  api-db:
    build:
      context: ./seek/db 
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}