version: "3.8"
services: 
  seek:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 5555:5000
    environment: 
      - FLASK_ENV=${FLASK_ENV}
      - DB_URL=${DB_URL}
      - APP_SETTINGS=${APP_SETTINGS}
    depends_on: 
      - api-db
  
  api-db:
    build:
      context: ./seek/db 
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}